name: testable
description: "Flutter Blueprint is a production-grade Flutter foundation designed to accelerate real-world app development. It provides a clean, scalable architecture with Riverpod integration, environment configuration, networking, authentication flows, error handling, logging, notifications, and complete testing scaffolding. Built to serve as a long-term base for enterprise and consumer applications, Flutter Blueprint focuses on maintainability, performance, and best practicesâ€”so teams can ship faster without compromising structure."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  auto_route: ^11.1.0
  auto_route_generator: ^10.2.5
  awesome_extensions: ^2.0.26
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dev: ^1.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_lints: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.2
  freezed_annotation: ^3.1.0
  iconsax: ^0.0.8
  json_annotation: ^4.9.0
  logger: ^2.6.2
  logging: ^1.3.0
  lottie: ^3.3.2
  retrofit: ^4.9.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  toastification: ^3.0.3


dev_dependencies:
  build_runner: ^2.10.1
  coverage: ^1.7.0
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mockito: ^5.5.1
  retrofit_generator: ^10.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - .env.test
    - assets/svgs/
  #   - images/a_dot_ham.jpeg

# Watch mode (what you're trying to run)
# fvm flutter pub run build_runner watch

# Clean build (if you have issues)
# fvm flutter pub run build_runner watch --delete-conflicting-outputs